// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf_gs-epjXSW5scVn8ckL1Cq76Ga8dvzQ',
    appId: '1:775898877631:web:a48123b0c2ba8e896d400a',
    messagingSenderId: '775898877631',
    projectId: 'movieapp-75d13',
    authDomain: 'movieapp-75d13.firebaseapp.com',
    storageBucket: 'movieapp-75d13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8NT7ixwU50FTCz_5cESgemQAgBRx520w',
    appId: '1:775898877631:android:c30f016833ce0e046d400a',
    messagingSenderId: '775898877631',
    projectId: 'movieapp-75d13',
    storageBucket: 'movieapp-75d13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEep54Ggb_qjK6yD4qkVrvLHb3ewjflIE',
    appId: '1:775898877631:ios:f746f8c2fb0649bc6d400a',
    messagingSenderId: '775898877631',
    projectId: 'movieapp-75d13',
    storageBucket: 'movieapp-75d13.appspot.com',
    iosClientId: '775898877631-tfnj5nvlghpc9d0a7mbukjj80spokamh.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlyMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEep54Ggb_qjK6yD4qkVrvLHb3ewjflIE',
    appId: '1:775898877631:ios:fa4b74b5dc2570bb6d400a',
    messagingSenderId: '775898877631',
    projectId: 'movieapp-75d13',
    storageBucket: 'movieapp-75d13.appspot.com',
    iosClientId: '775898877631-vv5uoad6b6q3b10b4g9q74tksgheojte.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlyMovie.RunnerTests',
  );
}
