FIREBASE_APP_ID = '1:775898877631:android:c30f016833ce0e046d400a'
GOOGLE_APPLICATION_CREDENTIALS = 'C:\Users\shark\Downloads'
FIREBASE_TOKEN = '1//03Dg_zK-4NLOfCgYIARAAGAMSNwF-L9Ir-8-XJcdNLurjiBSn9BlRnsItKOkuOZ8tvwlGH-qP0U2DMx24HTP0sWrLeYU_g-RGsW8'

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :build_test do
      gradle(
        task: 'assemble',
        build_type: 'Release'
      )
  end

    desc "Firebase Distribution"
    lane :distribute do
        gradle(
          task: 'assemble',
          build_type: 'Release',
        )

        firebase_app_distribution(
          app: FIREBASE_APP_ID,
          firebase_cli_token: FIREBASE_TOKEN,
          apk_path: "C:/Users/shark/StudioProjects/only_movie/build/app/outputs/flutter-apk/app-release.apk",
          testers: "romansk902@gmail.com",
          groups: "me",
          release_notes: "Second Firebase Distribution!",
        )
    end
end
