name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Fastlane Action
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'distribute'


#      - name: Set up Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2.16.0
#        with:
#          channel: 'stable'
#          architecture: x64
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Build APK
#        run: flutter build apk --release --split-per-abi

#      - name: Install Fastlane
#        run: |
#          gem install bundler
#          bundle install
#
#      - name: Run Fastlane
#        run: bundle exec fastlane distribute
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.GITHUB_TOKEN }}
