name: Deploy

on:
  workflow_dispatch:
    branches: ['main']

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello, world and OnlyMovie!"